import { describe, it, expect, vi, afterEach } from 'vitest'

import {
    getStartEnd,
    createDescription,
    isGeneratedDescription,
    withRetry,
} from './spotify'

const setNow = (iso) => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date(iso))
}

afterEach(() => {
    vi.useRealTimers()
})

describe('getStartEnd', () => {
    // release periods run Friday to Friday in New York time
    it('release period mid-week runs last Friday to this Friday', () => {
        setNow('2026-07-15T16:00:00Z') // Wednesday in New York

        const { start, end, unit, inclusivity } = getStartEnd(0)

        expect(start.format('YYYY-MM-DD')).toBe('2026-07-10')
        expect(end.format('YYYY-MM-DD')).toBe('2026-07-17')
        expect(unit).toBe('day')
        expect(inclusivity).toBe('[)')
    })

    it('release period on/after Friday runs this Friday to next Friday', () => {
        setNow('2026-07-18T16:00:00Z') // Saturday in New York

        const { start, end } = getStartEnd(0)

        expect(start.format('YYYY-MM-DD')).toBe('2026-07-17')
        expect(end.format('YYYY-MM-DD')).toBe('2026-07-24')
    })

    it('release period on Sunday still uses the most recent Friday', () => {
        setNow('2026-07-19T16:00:00Z') // Sunday in New York

        const { start, end } = getStartEnd(0)

        expect(start.format('YYYY-MM-DD')).toBe('2026-07-17')
        expect(end.format('YYYY-MM-DD')).toBe('2026-07-24')
    })

    it('today spans the whole local day', () => {
        setNow('2026-07-15T16:00:00Z')

        const { start, end } = getStartEnd(1)

        expect(start.format('YYYY-MM-DD HH:mm')).toBe('2026-07-15 00:00')
        expect(end.format('YYYY-MM-DD HH:mm')).toBe('2026-07-15 23:59')
    })

    it('this week spans Sunday through Saturday', () => {
        setNow('2026-07-15T16:00:00Z')

        const { start, end } = getStartEnd(2)

        expect(start.format('YYYY-MM-DD')).toBe('2026-07-12')
        expect(end.format('YYYY-MM-DD')).toBe('2026-07-18')
    })

    it('this month spans the calendar month', () => {
        setNow('2026-07-15T16:00:00Z')

        const { start, end } = getStartEnd(3)

        expect(start.format('YYYY-MM-DD')).toBe('2026-07-01')
        expect(end.format('YYYY-MM-DD')).toBe('2026-07-31')
    })

    it('this year spans the calendar year', () => {
        setNow('2026-07-15T16:00:00Z')

        const { start, end } = getStartEnd(4)

        expect(start.format('YYYY-MM-DD')).toBe('2026-01-01')
        expect(end.format('YYYY-MM-DD')).toBe('2026-12-31')
    })
})

describe('createDescription', () => {
    it('embeds the range in the description', () => {
        expect(createDescription('a', 'b')).toContain('[a - b]')
    })
})

describe('isGeneratedDescription', () => {
    it('matches descriptions in the current format', () => {
        expect(
            isGeneratedDescription(createDescription('Thu, Jan 1, 2026', 'Thu, Dec 31, 2026'))
        ).toBe(true)
    })

    it('matches descriptions from older versions of the app', () => {
        expect(
            isGeneratedDescription(
                'Generated by https://github.com/donaldma/spotify-liked [Thu, Jan 1, 2026 - Thu, Dec 31, 2026]'
            )
        ).toBe(true)
    })

    it('does not match other playlist descriptions', () => {
        expect(isGeneratedDescription('My mixtape')).toBe(false)
        expect(isGeneratedDescription('')).toBe(false)
    })
})

describe('withRetry', () => {
    it('returns the result on success', async () => {
        await expect(withRetry(() => Promise.resolve('ok'))).resolves.toBe(
            'ok'
        )
    })

    it('retries 429 after the retry-after delay', async () => {
        vi.useFakeTimers()
        const request = vi
            .fn()
            .mockRejectedValueOnce({
                statusCode: 429,
                headers: { 'retry-after': '2' },
            })
            .mockResolvedValue('ok')

        const promise = withRetry(request)
        await vi.advanceTimersByTimeAsync(3000)

        await expect(promise).resolves.toBe('ok')
        expect(request).toHaveBeenCalledTimes(2)
    })

    it('retries transient 5xx errors', async () => {
        vi.useFakeTimers()
        const request = vi
            .fn()
            .mockRejectedValueOnce({ statusCode: 502 })
            .mockResolvedValue('ok')

        const promise = withRetry(request)
        await vi.advanceTimersByTimeAsync(1000)

        await expect(promise).resolves.toBe('ok')
        expect(request).toHaveBeenCalledTimes(2)
    })

    it('does not retry non-retryable errors', async () => {
        const request = vi.fn().mockRejectedValue({ statusCode: 400 })

        await expect(withRetry(request)).rejects.toMatchObject({
            statusCode: 400,
        })
        expect(request).toHaveBeenCalledTimes(1)
    })

    it('gives up after exhausting retries', async () => {
        vi.useFakeTimers()
        const request = vi.fn().mockRejectedValue({ statusCode: 503 })

        const promise = withRetry(request, 2)
        const assertion = expect(promise).rejects.toMatchObject({
            statusCode: 503,
        })
        await vi.advanceTimersByTimeAsync(5000)
        await assertion

        expect(request).toHaveBeenCalledTimes(3)
    })
})
